# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
<<<<<<< HEAD
=======
  fail_on_warning: true
>>>>>>> starbase/main

# Optionally build your docs in additional formats such as PDF
# formats:
#  - pdf
#  - epub

build:
  os: ubuntu-24.04
  tools:
<<<<<<< HEAD
    python: "3.10"
=======
    python: "3.12"
>>>>>>> starbase/main
  jobs:
    post_checkout:
      - git fetch --tags --unshallow # Also fetch tags
    post_system_dependencies:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
<<<<<<< HEAD
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs
=======
      - make setup-docs UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}"
    build:
      html:
        - make docs UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" DOCS_OUTPUT="$READTHEDOCS_OUTPUT/html/"
>>>>>>> starbase/main
