name: dev
base: ubuntu@26.04
sdks:
  - name: uv
  - name: copilot
  - name: project-craft

actions:
  format: make format
  lint: make lint
  test: make test
  test-fast: make test-fast
  test-slow: make test-slow
  test-find-slow: make test-find-slow
  docs: make docs
  pack: make pack
  clean: make clean
  copilot: copilot
