name: Check policy
on:
  pull_request:

jobs:
  policy:
    uses: canonical/starflow/.github/workflows/policy.yaml@main
    with:
      osv-extra-args: "--config=osv-scanner.toml"
      osv-exclude-paths: |
        docs
      uv-export-no-groups: |
        docs
        docs-sphinx-stack
