name: Check policy
on:
  pull_request:

jobs:
  policy:
    permissions:
      actions: read
      contents: read
      pull-requests: read
      security-events: write
    uses: canonical/starflow/.github/workflows/policy.yaml@main
