name: QA
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:

jobs:
  lint:
    uses: lengau/starflow/.github/workflows/lint.yaml@work/lint-reusable
  python-tests:
    uses: lengau/starflow/.github/workflows/test-python.yaml@work/python-tests
    # with:
      # integration-platforms: '["ubuntu-latest"]'
