name: Release
on:
  push:
    tags:
      # These tags should be protected, remember to enable the rule:
      # https://github.com/canonical/starbase/settings/tag_protection
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      # For development only!
      - work/release-workflow

permissions:
  contents: write

jobs:
  source-wheel:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch tag annotations
        run: |
          # Note: we fetch the tags here instead of using actions/checkout's "fetch-tags"
          # because of https://github.com/actions/checkout/issues/1467
          git fetch --force --tags --depth 1
      - name: Set up uv
        run: |
          sudo snap install --classic astral-uv
      - name: Build packages
        run: |
          uv build
          uv tool run twine check dist/*
      - name: Upload pypi packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypi-packages
          path: dist/
      - name: Ensure the tag is a valid release tag.
        run: |
          git describe --dirty --long --match '[0-9]*.[0-9]*.[0-9]*' --exclude '*[^0-9.]*'
  pypi:
    needs: ["source-wheel"]
    runs-on: [self-hosted]
    if: github.ref_type == 'tag'
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Get packages
        uses: actions/download-artifact@v4
        with:
          name: pypi-packages
          path: dist/
      - name: Publish to pypi
        # Note: this action uses PyPI's support for Trusted Publishers
        # It needs a configuration on the PyPI project - see:
        # https://docs.pypi.org/trusted-publishers/adding-a-publisher/#github-actions
        uses: pypa/gh-action-pypi-publish@release/v1
  github-release:
    needs: ["source-wheel"]
    runs-on: [self-hosted]
    if: github.ref_type == 'tag'
    steps:
      - name: Get pypi artifacts
        uses: actions/download-artifact@v4
        with:
          name: pypi-packages
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          # Add wheel and source tarball
          files: |
            *.whl
            *.tar.gz
