name: test
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install tools
        run: |
          make setup
      - name: Run Linters
        run: |
          make -k lint
      - name: conventional commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "build,chore,ci,docs,feat,fix,perf,refactor,style,test"
  test:
    strategy:
      matrix:
        class: [unit, integration]
        platform: [ubuntu-latest, windows-latest, macos-latest]
        resolution: [highest]
        include:
          - platform: ubuntu-latest
            class: unit
            resolution: lowest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install tools
        run: |
          make setup
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
            3.11
            3.12
            3.13-dev
      - name: Configure venv and test
        shell: bash
        run: |
          for python_version in 3.10 3.11 3.12 3.13; do
            echo "::group::Python $python_version"
            uv sync --python=$python_version --reinstall --resolution=${{ matrix.resolution }}
            make test-${{ matrix.class }}
            echo "::endgroup::"
          done
        env:
          PYTEST_ADDOPTS: "--no-header -vv -rN"
      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          name: coverage-${{ matrix.class }}-${{ matrix.python-version }}-${{ matrix.platform }}
          files: .coverage*.xml
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.class }}-${{ matrix.python-version }}-${{ matrix.platform }}-${{ matrix.resolution }}
          path: |
            ./.results.*.xml
            ./.coverage.*.xml
