name: TICS
on:
  push:
    branches:
      - "main"
      # For troubleshooting
      - "work/tiobe**"

permissions: read-all

jobs:
  TICS:
    uses: canonical/starflow/.github/workflows/tics.yaml@main
    with:
      project: "craft-platforms"
    secrets: inherit
